include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DNDIcon16Prefs
DNDIcon16Prefs_FILES = DNDIRootListController.m
DNDIcon16Prefs_FRAMEWORKS = UIKit Foundation CoreFoundation
DNDIcon16Prefs_PRIVATE_FRAMEWORKS = Preferences
DNDIcon16Prefs_CFLAGS = -fobjc-arc -Wall -Wextra -Wno-unused-parameter
DNDIcon16Prefs_INSTALL_PATH = /Library/PreferenceBundles
DNDIcon16Prefs_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
